"""transaction2

Revision ID: 6f4df3b5e155
Revises: 8af1cd3be673
Create Date: 2023-01-05 22:18:19.891760

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6f4df3b5e155'
down_revision = '8af1cd3be673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balance', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance', type_='unique')
    # ### end Alembic commands ###
